name: Render assignment_example.pdf
on: push
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: further-statistics-1.typ
      # Now Typst is installed and packages will be cached!
      - run: typst compile further-statistics-1.typ fs1.pdf
